# Match Maker
FROM node:18

RUN mkdir /Backend
WORKDIR /Backend
COPY ./Backend/package.json /Backend/
RUN npm install
RUN npm install pm2 -g


COPY ./Backend /Backend/

# CMD npm run start
# CMD npm run cluster
CMD ["pm2-runtime", "ecosystem.config.cjs"]