# Game Server
FROM node:18

RUN mkdir /EngineServer
WORKDIR /EngineServer
COPY ./EngineServer/package.json /EngineServer/
RUN npm install
RUN npm install pm2 -g

COPY ./EngineServer /EngineServer/

# CMD node --inspect ./src/index.js
CMD ["pm2-runtime", "ecosystem.config.cjs"]

# CMD npm run start